#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + X + H2 <=> H* + H*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.046, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 1,
    label = "O* + H* <=> X + OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.28e+21,'cm^2/(mol*s)'), n=0, Ea=(11200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 2,
    label = "X + H2O <=> H2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.75, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 3,
    label = "O* + H2O* <=> OH* + OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+20,'cm^2/(mol*s)'), n=0, Ea=(43100,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 4,
    label = "H* + OH* <=> X + H2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.04e+21,'cm^2/(mol*s)'), n=0, Ea=(66220,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 5,
    label = "X + CO <=> CO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.84, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 6,
    label = "X + CO2 <=> CO2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 7,
    label = "O* + CO* <=> X + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+21,'cm^2/(mol*s)'), n=0, Ea=(117600,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 8,
    label = "H* + CO2* <=> OH* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+19,'cm^2/(mol*s)'), n=0, Ea=(8400,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 9,
    label = "H2 + CO <=> CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+09,'cm^3/(mol*s)'), n=1.16, Ea=(343.506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;H2]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;H2]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 10,
    label = "H2O + CO <=> HCOOH",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.254,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO;RO_H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;RO_H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 11,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 12,
    label = "CO + CH3OH <=> HCOOCH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.127,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;CsO_H]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;CsO_H]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 13,
    label = "H* + CO2 <=> HCOO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(109.582,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 109.5 to 109.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 109.5 to 109.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 14,
    label = "HCOO* <=> COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'1/s'), n=0, Ea=(100,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
family: Surface_Migration
""",
)

entry(
    index = 15,
    label = "H* + CO2 <=> COOH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(143.333,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 142.9 to 143.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 142.9 to 143.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 16,
    label = "H* + CH2O <=> CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 17,
    label = "OH* + CH2O <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 18,
    label = "H* + HCOOH <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(84.8043,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 19,
    label = "X + X + H2O <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.0083, n=0, Ea=(39.8149,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 36.5 to 39.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 36.5 to 39.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 20,
    label = "X + X + CH2O <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=6.2e-05, n=0, Ea=(26.7776,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 21,
    label = "X + CH2O <=> CH2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 22,
    label = "X + X + HCOOH <=> OH* + HCO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0006595, n=0, Ea=(47.8402,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 23,
    label = "X + X + HCOOH <=> H* + HCOO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.00415, n=0, Ea=(21.8065,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 24,
    label = "X + X + HCOOH <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=3.1e-05, n=0, Ea=(55.2202,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 25,
    label = "X + X + CH3OH <=> H* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.00415, n=0, Ea=(20.92,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 26,
    label = "X + CH3OH <=> CH3OH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 27,
    label = "X + X + HCOOCH3 <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0006595, n=0, Ea=(37.656,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 28,
    label = "X + HCO* <=> H* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.71e+17,'m^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [Combined;VacantSite]
    family: Surface_Dissociation"""),
    longDesc = 
"""
Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 29,
    label = "X + HCOO* <=> O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(178.353,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 30,
    label = "X + COOH* <=> OH* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(54300,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 44 HOCXO_1 + Ni_4 <=> OCX_3 + HOX_5 in Surface_Dissociation/training
    This reaction matched rate rule [Combined;VacantSite]
    family: Surface_Dissociation"""),
    longDesc = 
"""
Matched reaction 44 HOCXO_1 + Ni_4 <=> OCX_3 + HOX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 31,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 32,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Cdd;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Cdd;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 33,
    label = "OH* + CO* <=> O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-H]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 34,
    label = "X + H2 <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 35,
    label = "X + CO <=> COX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(26.4446,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW
    Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 36,
    label = "H* + CO <=> CHOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R#R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R#R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 37,
    label = "X + HCOOH <=> formic_acidX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 38,
    label = "CH3O* <=> OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'1/s'), n=0, Ea=(100,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Migration
""",
)

entry(
    index = 39,
    label = "X + X + CH3OH <=> H* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=9.3e-05, n=0, Ea=(26.7776,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 40,
    label = "X + CH3O2* <=> O* + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(135.649,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 41,
    label = "H* + CH2O <=> OC[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 42,
    label = "X + HCOOCH3 <=> methyl_formateX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(15.28,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW
    Ea raised from 0.0 to 15.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 15.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 43,
    label = "X + X + OCO <=> H* + CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.00415, n=0, Ea=(31.0705,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 44,
    label = "X + X + OCO <=> OH* + OC[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.001319, n=0, Ea=(37.656,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 45,
    label = "X + OCO <=> OCO.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 46,
    label = "X + X + CH3OH <=> OH* + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0006595, n=0, Ea=(50.1722,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 49.8 to 50.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
Ea raised from 49.8 to 50.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 47,
    label = "X + X + HCOOCH3 <=> HCOO* + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0006595, n=0, Ea=(54.7876,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 48,
    label = "X + CH3O* <=> O* + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(204.095,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 49,
    label = "X + X + CH4 <=> H* + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0009, n=0, Ea=(72000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 50,
    label = "X + O* + CH4 <=> OH* + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+18,'cm^5/(mol^2*s)'), n=0.7, Ea=(42000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 51,
    label = "X + OH* + CH4 <=> H2O* + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(10000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 52,
    label = "CO2 + CH4 <=> HCOOCH3",
    degeneracy = 8.0,
    kinetics = Arrhenius(A=(36240,'cm^3/(mol*s)'), n=2.83, Ea=(331.373,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Estimated using template [CO2;C_methane] for rate rule [CO2_Od;C_methane]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 8.0
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Estimated using template [CO2;C_methane] for rate rule [CO2_Od;C_methane]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 8.0
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 53,
    label = "X + CH4 <=> C.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 54,
    label = "CH3O2* <=> OC(O)[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'1/s'), n=0, Ea=(100,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Migration
""",
)

entry(
    index = 55,
    label = "H* + HCOOH <=> OC(O)[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(95.816,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 56,
    label = "X + X + OCO <=> H* + OC(O)[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=6.2e-05, n=0, Ea=(42.0822,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 57,
    label = "CO + HCO* <=> C2HO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*C;R#R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*C;R#R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 58,
    label = "CH2O + CH3O* <=> COCO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 59,
    label = "H* + HCOOCH3 <=> COCO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(88.1952,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 60,
    label = "X + X + HCOOCH3 <=> H* + O=COC[Pt]",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=9.3e-05, n=0, Ea=(43.3376,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 61,
    label = "HCO* + CH2O <=> O=COC[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*C;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*C;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 62,
    label = "H* + HCOOCH3 <=> COC(O)[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(99.2068,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*H;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*H;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 63,
    label = "HCOOH + CH3X <=> COC(O)[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [*C;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Exact match found for rate rule [*C;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 64,
    label = "COCO[Pt] <=> COC(O)[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'1/s'), n=0, Ea=(100,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Migration
""",
)

entry(
    index = 65,
    label = "X + X + COCO <=> CH3O* + OC[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0006595, n=0, Ea=(37.656,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 66,
    label = "X + X + COCO <=> CH3X + CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0006595, n=0, Ea=(60.6608,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [R-R;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 67,
    label = "X + X + COCO <=> H* + COCO[Pt]",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.002075, n=0, Ea=(31.0705,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [R-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 68,
    label = "X + X + COCO <=> H* + COC(O)[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=3.1e-05, n=0, Ea=(42.0822,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 69,
    label = "X + COCO <=> COCO.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(15.28,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW
    Ea raised from 0.0 to 15.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 15.3 kJ/mol to match endothermicity of reaction.
""",
)

