#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "H2 + CO <=> CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+09,'cm^3/(mol*s)'), n=1.16, Ea=(343.506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;H2]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;H2]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 1,
    label = "H2O + CO <=> HCOOH",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.254,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO;RO_H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;RO_H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 2,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 3,
    label = "CO + CH3OH <=> HCOOCH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.127,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;CsO_H]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;CsO_H]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 4,
    label = "H* + CO2 <=> HCOO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(130.64,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 5,
    label = "HCOO* <=> COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.11289e+12,'s^-1'), n=0, Ea=(60.5233,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1]
    Euclidian distance = 0
    family: Surface_Migration"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1]
Euclidian distance = 0
family: Surface_Migration
""",
)

entry(
    index = 6,
    label = "H* + CO2 <=> COOH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 7,
    label = "H* + CH2O <=> CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 8,
    label = "OH* + CH2O <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 9,
    label = "H* + HCOOH <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.4657,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 10,
    label = "X + X + H2 <=> H* + H*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 1 H2 + Ni_3 + Ni_4 <=> HX_3 + HX_4 in Surface_Adsorption_Dissociative/training
    This reaction matched rate rule [H2;VacantSite1;VacantSite2]
    family: Surface_Adsorption_Dissociative
    metal: None"""),
    longDesc = 
"""
Matched reaction 1 H2 + Ni_3 + Ni_4 <=> HX_3 + HX_4 in Surface_Adsorption_Dissociative/training
This reaction matched rate rule [H2;VacantSite1;VacantSite2]
family: Surface_Adsorption_Dissociative
metal: None
""",
)

entry(
    index = 11,
    label = "X + CO2 <=> CO2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(26.4446,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW
    Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 12,
    label = "X + X + H2O <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(59.6227,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 59.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 59.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 13,
    label = "X + H2O <=> H2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 14,
    label = "X + X + CH2O <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 15,
    label = "X + CH2O <=> CH2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 16,
    label = "X + X + HCOOH <=> OH* + HCO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(28.3322,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 28.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 28.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 17,
    label = "X + X + HCOOH <=> H* + HCOO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(92.5817,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 92.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 92.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 18,
    label = "X + X + HCOOH <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(9.54988,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 9.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 9.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 19,
    label = "X + X + CH3OH <=> H* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(15.1832,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 15.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 15.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 20,
    label = "X + CH3OH <=> CH3OH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 21,
    label = "X + X + HCOOCH3 <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(4.92873,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 4.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 4.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 22,
    label = "X + OH* <=> O* + H*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.452e+17,'m^2/(mol*s)'), n=0, Ea=(38.7417,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 15 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 15 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 23,
    label = "X + H2O* <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.879e+15,'m^2/(mol*s)'), n=0, Ea=(18.4454,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 14 H2O* + Cu4 <=> OH* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None
    Ea raised from 20.3 to 77.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 14 H2O* + Cu4 <=> OH* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
Ea raised from 20.3 to 77.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 24,
    label = "O* + CO* <=> X + CO2*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.06e+16,'m^2/(mol*s)'), n=0, Ea=(14.9894,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 9 CO* + O* <=> CO2* + Cu4 in Surface_Dissociation_Double_vdW/training
    This reaction matched rate rule [CO2;VacantSite]
    family: Surface_Dissociation_Double_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 9 CO* + O* <=> CO2* + Cu4 in Surface_Dissociation_Double_vdW/training
This reaction matched rate rule [CO2;VacantSite]
family: Surface_Dissociation_Double_vdW
metal: None
""",
)

entry(
    index = 25,
    label = "H* + CO* <=> X + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.14e+17,'m^2/(mol*s)'), n=0, Ea=(22.8299,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 26 OCX_3 + HX_5 <=> CXHO_1 + Ni_4 in Surface_Dissociation/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 26 OCX_3 + HX_5 <=> CXHO_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 26,
    label = "X + HCOO* <=> O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.733e+16,'m^2/(mol*s)'), n=0, Ea=(10.8385,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 28 HCOO* + Ni_4 <=> HCO* + OX_3 in Surface_Dissociation/training
    This reaction matched rate rule [O-C;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 28 HCOO* + Ni_4 <=> HCO* + OX_3 in Surface_Dissociation/training
This reaction matched rate rule [O-C;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 27,
    label = "OH* + CO* <=> X + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.02e+14,'m^2/(mol*s)'), n=0, Ea=(11.5,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 1 OCX_3 + HOX_5 <=> HOCXO_1 + Ni_4 in Surface_Dissociation/training
    This reaction matched rate rule [C-O;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 1 OCX_3 + HOX_5 <=> HOCXO_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [C-O;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 28,
    label = "H* + HCO* <=> X + CH2O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.932e+17,'m^2/(mol*s)'), n=0, Ea=(10.8385,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 30 HCO* + H* <=> CH2O* + Cu4 in Surface_Dissociation_vdW/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 30 HCO* + H* <=> CH2O* + Cu4 in Surface_Dissociation_vdW/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 29,
    label = "H* + CH3O* <=> X + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.349e+22,'m^2/(mol*s)'), n=0, Ea=(10.8385,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 25 CH3O* + H* <=> CH3OH_2* + Cu4 in Surface_Dissociation_vdW/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 25 CH3O* + H* <=> CH3OH_2* + Cu4 in Surface_Dissociation_vdW/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 30,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 31,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Cdd;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Cdd;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 32,
    label = "H* + CO2* <=> X + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.243e+18,'m^2/(mol*s)'), n=0, Ea=(24.5876,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 17 CO2* + H* <=> HCOO* + Cu5 in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [O=C=O;H*]
    family: Surface_Addition_Single_vdW
    metal: None
    Ea raised from 83.9 to 102.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 17 CO2* + H* <=> HCOO* + Cu5 in Surface_Addition_Single_vdW/training
This reaction matched rate rule [O=C=O;H*]
family: Surface_Addition_Single_vdW
metal: None
Ea raised from 83.9 to 102.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 33,
    label = "X + COOH* <=> H* + CO2*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.028e+17,'m^2/(mol*s)'), n=0, Ea=(28.3645,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 11 COOH* + Cu5 <=> CO2_2* + H* in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [CO2;H*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 11 COOH* + Cu5 <=> CO2_2* + H* in Surface_Addition_Single_vdW/training
This reaction matched rate rule [CO2;H*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 34,
    label = "H* + CH2O* <=> X + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.167e+17,'m^2/(mol*s)'), n=0, Ea=(5.53453,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 24 CH2O* + H* <=> CH3O_1* + Cu5 in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [O=C;H*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 24 CH2O* + H* <=> CH3O_1* + Cu5 in Surface_Addition_Single_vdW/training
This reaction matched rate rule [O=C;H*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 35,
    label = "OH* + OH* <=> O* + H2O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(5.691e+16,'m^2/(mol*s)'), n=0, Ea=(14.0669,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 16 OH_2* + OH_4* <=> H2O* + O* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 16 OH_2* + OH_4* <=> H2O* + O* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=O]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 36,
    label = "O* + HCO* <=> OH* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.298e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 39 O* + HCO* <=> OH* + CO* in Surface_Abstraction/training
    This reaction matched rate rule [O;*-C-H]
    family: Surface_Abstraction
    metal: None"""),
    longDesc = 
"""
Matched reaction 39 O* + HCO* <=> OH* + CO* in Surface_Abstraction/training
This reaction matched rate rule [O;*-C-H]
family: Surface_Abstraction
metal: None
""",
)

entry(
    index = 37,
    label = "O* + CH2O* <=> OH* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.44854e+10,'m^2/(mol*s)'), n=1.38075, Ea=(147.821,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=O] for rate rule [C-R;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=O] for rate rule [C-R;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 38,
    label = "O* + CH2O* <=> H* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.44854e+10,'m^2/(mol*s)'), n=1.38075, Ea=(147.821,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 39,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.07385e+13,'m^2/(mol*s)'), n=1.08916, Ea=(187.22,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-C;*=O] for rate rule [O-C-3R;*=O]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-C;*=O] for rate rule [O-C-3R;*=O]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 40,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.22427e+10,'m^2/(mol*s)'), n=1.38075, Ea=(147.821,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 16 used for O-R;*=O
    Exact match found for rate rule [O-R;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 16 used for O-R;*=O
Exact match found for rate rule [O-R;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 41,
    label = "O* + CH3OH* <=> H* + CH3O2*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.26728e+11,'m^2/(mol*s)'), n=1.38075, Ea=(147.821,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 42,
    label = "OH* + CO2* <=> O* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(89.6128,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 89.3 to 89.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 89.3 to 89.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 43,
    label = "OH* + CO2* <=> O* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 44,
    label = "X + CH3O2* <=> OH* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.401e+17,'m^2/(mol*s)'), n=0, Ea=(17.0648,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 23 CH3O2* + Cu5 <=> CH2O* + OH* in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [O=C;HO*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 23 CH3O2* + Cu5 <=> CH2O* + OH* in Surface_Addition_Single_vdW/training
This reaction matched rate rule [O=C;HO*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 45,
    label = "OH* + CH2O* <=> O* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.814e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
Euclidian distance = 1.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 46,
    label = "OH* + HCO* <=> H2O* + CO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.261e+17,'m^2/(mol*s)'), n=0, Ea=(6.91816,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 40 OH_2* + HCO* <=> H2O* + CO* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=C=R]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 40 OH_2* + HCO* <=> H2O* + CO* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=C=R]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 47,
    label = "H2O* + CO* <=> H* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 48,
    label = "H2O* + CO2* <=> OH* + HCOO*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.27893e+10,'m^2/(mol*s)'), n=1.29863, Ea=(181.505,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C=O;O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C=O;O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 49,
    label = "OH* + COOH* <=> H2O* + CO2*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(3.398e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 12 COOH* + OH* <=> CO2* + H2O* in Surface_Dual_Adsorption_vdW/training
    This reaction matched rate rule [CO2;O-R]
    family: Surface_Dual_Adsorption_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 12 COOH* + OH* <=> CO2* + H2O* in Surface_Dual_Adsorption_vdW/training
This reaction matched rate rule [CO2;O-R]
family: Surface_Dual_Adsorption_vdW
metal: None
""",
)

entry(
    index = 50,
    label = "H2O* + CH2O* <=> OH* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.13946e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 51,
    label = "H2O* + CH2O* <=> H* + CH3O2*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.13946e+10,'m^2/(mol*s)'), n=1.29863, Ea=(99.6511,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 52,
    label = "CO* + CH2O* <=> HCO* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 53,
    label = "HCO* + CH3O* <=> CO* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.572e+16,'m^2/(mol*s)'), n=0, Ea=(8.76301,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 45 CH3O* + HCO* <=> CH3OH* + CO* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=C=R]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 45 CH3O* + HCO* <=> CH3OH* + CO* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=C=R]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 54,
    label = "CO2* + HCO* <=> CO* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(85.7506,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;*C-H] for rate rule [O=C=O;*C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;*C-H] for rate rule [O=C=O;*C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 55,
    label = "CO2* + HCO* <=> CO* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*C-H] for rate rule [CO2;*C-H]
    Euclidian distance = 4.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C-H] for rate rule [CO2;*C-H]
Euclidian distance = 4.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 56,
    label = "CO2* + CH2O* <=> HCO* + HCOO*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.27893e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 57,
    label = "CO2* + CH2O* <=> HCO* + COOH*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.27893e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate2] for rate rule [CO2;C-R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate2] for rate rule [CO2;C-R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 58,
    label = "CO2* + CH3OH* <=> HCOO* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.13946e+10,'m^2/(mol*s)'), n=1.29863, Ea=(161.221,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C=O;O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C=O;O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 59,
    label = "CO2* + CH3OH* <=> COOH* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.13946e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 12 used for CO2;O-R
    Exact match found for rate rule [CO2;O-R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 12 used for CO2;O-R
Exact match found for rate rule [CO2;O-R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 60,
    label = "HCO* + CH2O* <=> CO* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.398e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 44 CH2O* + HCO* <=> CH3O* + CO* in Surface_Adsorption_Abstraction_vdW/training
    This reaction matched rate rule [O=C;*C-H]
    family: Surface_Adsorption_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 44 CH2O* + HCO* <=> CH3O* + CO* in Surface_Adsorption_Abstraction_vdW/training
This reaction matched rate rule [O=C;*C-H]
family: Surface_Adsorption_Abstraction_vdW
metal: None
""",
)

entry(
    index = 61,
    label = "COOH* + CH2O* <=> CO* + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.814e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [O=C;*C-R]
    Euclidian distance = 0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [O=C;*C-R]
Euclidian distance = 0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 62,
    label = "CH2O* + CH2O* <=> HCO* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.13946e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 63,
    label = "CH2O* + CH3OH* <=> CH3O* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5.69732e+09,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
    Euclidian distance = 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
Euclidian distance = 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 64,
    label = "X + H2 <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 65,
    label = "O* + [H][H].[Pt] <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.44854e+10,'m^2/(mol*s)'), n=1.38075, Ea=(147.821,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 66,
    label = "[H][H].[Pt] + CO* <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=C=R] for rate rule [H-H;*=C=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C=R] for rate rule [H-H;*=C=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 67,
    label = "[H][H].[Pt] + CO2* <=> H* + HCOO*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.27893e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 68,
    label = "[H][H].[Pt] + CO2* <=> H* + COOH*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.27893e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate2] for rate rule [CO2;H-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate2] for rate rule [CO2;H-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 69,
    label = "[H][H].[Pt] + CH2O* <=> H* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.13946e+10,'m^2/(mol*s)'), n=1.29863, Ea=(92.7385,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;H-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;H-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

