#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + X + H2 <=> H* + H*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 1,
    label = "X + CO <=> CO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.5, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 2,
    label = "OH* + HCO* <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.28e+16,'m^2/(mol*s)'), n=0.263, Ea=(15900,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 3,
    label = "H2 + CO <=> CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+09,'cm^3/(mol*s)'), n=1.16, Ea=(343.506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;H2]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;H2]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 4,
    label = "H2O + CO <=> HCOOH",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.254,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO;RO_H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;RO_H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 5,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 6,
    label = "CO + CH3OH <=> HCOOCH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.127,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;CsO_H]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;CsO_H]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 7,
    label = "X + H2O <=> H2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 5 H2O + X <=> H2OX in Surface_Adsorption_vdW/training
    This reaction matched rate rule [H2O;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 5 H2O + X <=> H2OX in Surface_Adsorption_vdW/training
This reaction matched rate rule [H2O;VacantSite]
family: Surface_Adsorption_vdW
metal: None
""",
)

entry(
    index = 8,
    label = "X + CO2 <=> CO2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=7e-06, n=0, Ea=(26444.6,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 7 CO2 + X <=> CO2X in Surface_Adsorption_vdW/training
    This reaction matched rate rule [Adsorbate;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None
    Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 7 CO2 + X <=> CO2X in Surface_Adsorption_vdW/training
This reaction matched rate rule [Adsorbate;VacantSite]
family: Surface_Adsorption_vdW
metal: None
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 9,
    label = "H* + CO2 <=> HCOO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(82.0048,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 10,
    label = "HCOO* <=> COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.11289e+12,'s^-1'), n=0, Ea=(60.5233,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1]
    Euclidian distance = 0
    family: Surface_Migration"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1]
Euclidian distance = 0
family: Surface_Migration
""",
)

entry(
    index = 11,
    label = "H* + CO2 <=> COOH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 12,
    label = "X + CH2O <=> CH2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1e-12, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 13,
    label = "H* + CH2O <=> CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 14,
    label = "OH* + CH2O <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 15,
    label = "H* + HCOOH <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 16,
    label = "X + CH3OH <=> CH3OH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1e-12, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 17,
    label = "X + X + H2O <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(50.3265,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 50.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 50.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 18,
    label = "X + X + CH2O <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 19,
    label = "X + X + HCOOH <=> OH* + HCO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 20,
    label = "X + X + HCOOH <=> H* + HCOO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(64.1763,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 64.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 64.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 21,
    label = "X + X + HCOOH <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(30.6921,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 30.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 30.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 22,
    label = "X + X + CH3OH <=> H* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(5.887,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 5.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 5.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 23,
    label = "X + X + HCOOCH3 <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 24,
    label = "X + OH* <=> O* + H*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.25e+16,'m^2/(mol*s)'), n=0.188, Ea=(29600,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 32 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 32 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 25,
    label = "X + H2O* <=> H* + OH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.67e+17,'m^2/(mol*s)'), n=-0.086, Ea=(92.9,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 26,
    label = "X + H2O* <=> H* + OH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.67e+17,'m^2/(mol*s)'), n=-0.086, Ea=(92.9,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [Combined;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 27,
    label = "X + CO2* <=> O* + CO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.64e+19,'m^2/(mol*s)'), n=-1, Ea=(89300,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 42 CO2* + X_4 <=> CO* + O* in Surface_Dissociation_Double_vdW/training
    This reaction matched rate rule [CO2;VacantSite]
    family: Surface_Dissociation_Double_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 42 CO2* + X_4 <=> CO* + O* in Surface_Dissociation_Double_vdW/training
This reaction matched rate rule [CO2;VacantSite]
family: Surface_Dissociation_Double_vdW
metal: None
""",
)

entry(
    index = 28,
    label = "X + HCO* <=> H* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.71e+17,'m^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 29,
    label = "H* + CO2* <=> X + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.25e+20,'m^2/(mol*s)'), n=-0.475, Ea=(117.2,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;H*] for rate rule [O=C=O;H*]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;H*] for rate rule [O=C=O;H*]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 30,
    label = "X + HCOO* <=> O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.25e+16,'m^2/(mol*s)'), n=0.188, Ea=(29.6,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O;VacantSite] for rate rule [O-C;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [O;VacantSite] for rate rule [O-C;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation
""",
)

entry(
    index = 31,
    label = "H* + CO2* <=> X + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.25e+20,'m^2/(mol*s)'), n=-0.475, Ea=(117200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 45 CO2_2* + H* <=> COOH* + X_5 in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [CO2;H*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 45 CO2_2* + H* <=> COOH* + X_5 in Surface_Addition_Single_vdW/training
This reaction matched rate rule [CO2;H*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 32,
    label = "OH* + CO* <=> X + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.02e+14,'m^2/(mol*s)'), n=0, Ea=(108.004,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 1 OCX_3 + HOX_5 <=> HOCXO_1 + Ni_4 in Surface_Dissociation/training
    This reaction matched rate rule [C-O;VacantSite]
    family: Surface_Dissociation
    metal: None
    Ea raised from 11.5 to 108.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 1 OCX_3 + HOX_5 <=> HOCXO_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [C-O;VacantSite]
family: Surface_Dissociation
metal: None
Ea raised from 11.5 to 108.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 33,
    label = "X + CH2O* <=> H* + HCO*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(7.7e+16,'m^2/(mol*s)'), n=0.087, Ea=(55.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 12 used for C-H;VacantSite
    Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 12 used for C-H;VacantSite
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 34,
    label = "X + CH2O* <=> H* + HCO*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(5.99662e+17,'m^2/(mol*s)'), n=0.000333333, Ea=(75.8967,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 35,
    label = "H* + CH2O* <=> X + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.125e+20,'m^2/(mol*s)'), n=-0.475, Ea=(117.2,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;H*] for rate rule [O=C;H*]
    Euclidian distance = 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;H*] for rate rule [O=C;H*]
Euclidian distance = 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 36,
    label = "OH* + CH2O* <=> X + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.125e+20,'m^2/(mol*s)'), n=-0.475, Ea=(117.2,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;HO*]
    Euclidian distance = 2.8284271247461903
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;HO*]
Euclidian distance = 2.8284271247461903
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 37,
    label = "X + CH3OH* <=> H* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.67e+17,'m^2/(mol*s)'), n=-0.086, Ea=(92.9,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 29 used for O-H;VacantSite
    Exact match found for rate rule [O-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 29 used for O-H;VacantSite
Exact match found for rate rule [O-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 38,
    label = "X + CH3OH* <=> H* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.99831e+17,'m^2/(mol*s)'), n=0.000333333, Ea=(75.8967,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 39,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 40,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Cdd;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Cdd;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 41,
    label = "X + H2O* <=> H* + OH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.67e+17,'m^2/(mol*s)'), n=-0.086, Ea=(92.9,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [Combined;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 42,
    label = "X + H2O* <=> H* + OH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.67e+17,'m^2/(mol*s)'), n=-0.086, Ea=(92.9,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 29 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 43,
    label = "X + CH2O* <=> H* + HCO*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(5.99662e+17,'m^2/(mol*s)'), n=0.000333333, Ea=(75.8967,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 44,
    label = "X + CH2O* <=> H* + HCO*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(7.7e+16,'m^2/(mol*s)'), n=0.087, Ea=(55.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 12 used for C-H;VacantSite
    Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 12 used for C-H;VacantSite
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 45,
    label = "O* + CH2O* <=> H* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.78261e+20,'m^2/(mol*s)'), n=-0.1875, Ea=(155.55,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 46,
    label = "H2O* + CO* <=> H* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.78261e+20,'m^2/(mol*s)'), n=-0.1875, Ea=(175.938,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 47,
    label = "X + CH3OH* <=> H* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.99831e+17,'m^2/(mol*s)'), n=0.000333333, Ea=(75.8967,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 48,
    label = "X + CH3OH* <=> H* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.67e+17,'m^2/(mol*s)'), n=-0.086, Ea=(92.9,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 29 used for O-H;VacantSite
    Exact match found for rate rule [O-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 29 used for O-H;VacantSite
Exact match found for rate rule [O-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 49,
    label = "O* + CH3OH* <=> H* + CH3O2*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(7.17392e+20,'m^2/(mol*s)'), n=-0.1875, Ea=(155.55,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 50,
    label = "H2O* + CH2O* <=> H* + CH3O2*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(70.0482,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 70.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 70.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 51,
    label = "O* + H2O* <=> OH* + OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.14e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218400,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 34 H2O* + O* <=> OH_2* + OH_4* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 34 H2O* + O* <=> OH_2* + OH_4* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=O]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 52,
    label = "OH* + CO* <=> O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(24.8967,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 24 used for C=*;*OH
    Exact match found for rate rule [C=*;*OH]
    Euclidian distance = 0
    family: Surface_Abstraction
    Ea raised from 22.9 to 24.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
From training reaction 24 used for C=*;*OH
Exact match found for rate rule [C=*;*OH]
Euclidian distance = 0
family: Surface_Abstraction
Ea raised from 22.9 to 24.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 53,
    label = "OH* + CO2* <=> O* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(53.6827,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*O-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*O-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 54,
    label = "OH* + CO2* <=> O* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(38.9605,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 55,
    label = "O* + CH2O* <=> OH* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.81e+20,'m^2/(mol*s)'), n=-0.101, Ea=(92.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 21 used for C-R;*=O
    Exact match found for rate rule [C-R;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 21 used for C-R;*=O
Exact match found for rate rule [C-R;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 56,
    label = "OH* + CH2O* <=> O* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.845e+16,'m^2/(mol*s)'), n=0, Ea=(15.8999,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*O-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*O-R]
Euclidian distance = 2.23606797749979
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 57,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.07e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;*=O] for rate rule [O-C-3R;*=O]
    Euclidian distance = 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=O] for rate rule [O-C-3R;*=O]
Euclidian distance = 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 58,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.07e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 34 used for O-R;*=O
    Exact match found for rate rule [O-R;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 34 used for O-R;*=O
Exact match found for rate rule [O-R;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 59,
    label = "H2O* + CO* <=> OH* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.14e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 60,
    label = "H2O* + CO2* <=> OH* + HCOO*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(122.119,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;O-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 122.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;O-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 122.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 61,
    label = "H2O* + CO2* <=> OH* + COOH*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(88.6346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 88.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 88.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 62,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.07e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;*=O] for rate rule [O-C-3R;*=O]
    Euclidian distance = 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=O] for rate rule [O-C-3R;*=O]
Euclidian distance = 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 63,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.07e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 34 used for O-R;*=O
    Exact match found for rate rule [O-R;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 34 used for O-R;*=O
Exact match found for rate rule [O-R;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 64,
    label = "H2O* + CH2O* <=> OH* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(33.3401,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;O-R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 33.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;O-R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 33.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 65,
    label = "CO2* + HCO* <=> CO* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(44.0734,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-H]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-H]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 66,
    label = "CO2* + HCO* <=> CO* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(29.3512,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-H]
    Euclidian distance = 4.47213595499958
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-H]
Euclidian distance = 4.47213595499958
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 67,
    label = "CO* + CH2O* <=> HCO* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.81e+20,'m^2/(mol*s)'), n=-0.101, Ea=(92.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C-R;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [C-R;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 68,
    label = "HCO* + CH2O* <=> CO* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.845e+16,'m^2/(mol*s)'), n=0, Ea=(6.29062,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 69,
    label = "COOH* + CH2O* <=> CO* + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.845e+16,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-R]
Euclidian distance = 2.23606797749979
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 70,
    label = "CO* + CH3OH* <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.07e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 71,
    label = "CO2* + CH2O* <=> HCO* + HCOO*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(2.14023,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 2.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 2.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 72,
    label = "CO2* + CH2O* <=> HCO* + COOH*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;C-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;C-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 73,
    label = "CO2* + CH3OH* <=> HCOO* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(101.255,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;O-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 101.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;O-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 101.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 74,
    label = "CO2* + CH3OH* <=> COOH* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(67.771,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 67.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 67.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 75,
    label = "CH2O* + CH2O* <=> HCO* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 76,
    label = "CH2O* + CH3OH* <=> CH3O* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(12.4765,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;O-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 12.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;O-R]
Euclidian distance = 2.23606797749979
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 12.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 77,
    label = "X + X + CO2 <=> CO2X",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 78,
    label = "X + CO2* <=> CO2X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_vdW_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Surface_vdW_to_Bidentate
""",
)

entry(
    index = 79,
    label = "CO2X <=> O* + CO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(8.96e+10,'1/s'), n=0.422, Ea=(83.8892,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation
    Ea raised from 0.0 to 83.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
Ea raised from 0.0 to 83.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 80,
    label = "CO2X <=> O* + CO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(8.96e+10,'1/s'), n=0.422, Ea=(83.8892,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation
    Ea raised from 0.0 to 83.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
Ea raised from 0.0 to 83.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 81,
    label = "X + H2 <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1e-12, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 82,
    label = "X + [H][H].[Pt] <=> H* + H*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(5.99662e+17,'m^2/(mol*s)'), n=0.000333333, Ea=(75.8967,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R-H;VacantSite] for rate rule [H-H;VacantSite]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using template [R-H;VacantSite] for rate rule [H-H;VacantSite]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 83,
    label = "O* + [H][H].[Pt] <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.78261e+20,'m^2/(mol*s)'), n=-0.1875, Ea=(155.55,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 84,
    label = "[H][H].[Pt] + CO* <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.78261e+20,'m^2/(mol*s)'), n=-0.1875, Ea=(155.55,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 85,
    label = "[H][H].[Pt] + CO2* <=> H* + HCOO*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(62.234,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 62.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 62.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 86,
    label = "[H][H].[Pt] + CO2* <=> H* + COOH*",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(28.7498,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;H-H]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 28.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;H-H]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 28.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 87,
    label = "[H][H].[Pt] + CH2O* <=> H* + CH3O*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;H-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;H-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 88,
    label = "X + CO* <=> COX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(4.184,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 89,
    label = "X + HCO* <=> [Pt]OC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(4.184,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 90,
    label = "X + [Pt]OC=[Pt] <=> H* + COX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.71e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 48 used for C-H;VacantSite
    Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 48 used for C-H;VacantSite
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 91,
    label = "OH* + COX <=> O* + [Pt]OC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.4e+18,'m^2/(mol*s)'), n=0.101, Ea=(42.4,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 26 used for C#*;*OH
    Exact match found for rate rule [C#*;*OH]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
From training reaction 26 used for C#*;*OH
Exact match found for rate rule [C#*;*OH]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 92,
    label = "H2O* + COX <=> OH* + [Pt]OC=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.14e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*#C]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*#C]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 93,
    label = "COX + HCO* <=> CO* + [Pt]OC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.4e+18,'m^2/(mol*s)'), n=0.101, Ea=(42.4,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C#*;*R-H] for rate rule [C#*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C#*;*R-H] for rate rule [C#*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 94,
    label = "CO2* + [Pt]OC=[Pt] <=> COX + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(45.6964,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 95,
    label = "CO2* + [Pt]OC=[Pt] <=> COX + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(30.9742,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 96,
    label = "COX + CH2O* <=> HCO* + [Pt]OC=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.81e+20,'m^2/(mol*s)'), n=-0.101, Ea=(92.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C-R;Adsorbate1] for rate rule [C-R;*#C]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [C-R;Adsorbate1] for rate rule [C-R;*#C]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 97,
    label = "[Pt]OC=[Pt] + CH2O* <=> COX + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.845e+16,'m^2/(mol*s)'), n=0, Ea=(7.9136,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-R]
Euclidian distance = 2.23606797749979
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 98,
    label = "COX + CH3OH* <=> [Pt]OC=[Pt] + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.07e+20,'m^2/(mol*s)'), n=-0.274, Ea=(218.4,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*#C]
    Euclidian distance = 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*#C]
Euclidian distance = 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 99,
    label = "[H][H].[Pt] + COX <=> H* + [Pt]OC=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.78261e+20,'m^2/(mol*s)'), n=-0.1875, Ea=(155.55,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*#C]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*#C]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 100,
    label = "O* + CHX <=> X + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.59e+16,'m^2/(mol*s)'), n=0, Ea=(109900,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 101,
    label = "[Pt]OC=[Pt] <=> O* + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.96e+10,'1/s'), n=0.422, Ea=(3.04466,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation
    Ea raised from 0.0 to 3.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
Ea raised from 0.0 to 3.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 102,
    label = "CO* + [Pt]OC=[Pt] <=> CO2X + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;Donating] for rate rule [C=*;*R-O]
    Euclidian distance = 1.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;Donating] for rate rule [C=*;*R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

